server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

  application:
    name: pet_store_coming_be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rdsHostname}:${rdsPort}/${rdsDbName}?serverTimezone=UTC
    username: ${rdsUsername}
    password: ${rdsPassword}

  devtools:
    restart:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

aes:
  secret-key: ${aesSecretKey}

toss:
  payments:
    base-url: https://api.tosspayments.com/v1/
    secret-key: ${tossSecretKey}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.coming.pet_store_coming_be

jwt:
  secret-key: ${tokenSecretKey}
  expiration-time: 3600000
  refresh-expiration-time: 10800000

kakao:
  client-id: ${socialClientId}
  redirect-url: ${socialRedirectUrl}
  token-url: ${socialTokenUrl}

cors:
  allowed-origin: ${corsAllowedOrigin}
