server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

  application:
    name: pet_store_coming_be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}

  devtools:
    restart:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

aes:
  secret-key: ${aes.secret-key}

toss:
  payments:
    base-url: https://api.tosspayments.com/v1/
    secret-key: ${toss.secret-key}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.coming.pet_store_coming_be

jwt:
  secret-key: ${token.secret-key}
  expiration-time: 3600000
  refresh-expiration-time: 10800000

kakao:
  client-id: ${social.client-id}
  redirect-url: ${social.redirect-url}
  token-url: ${social.token-url}

cors:
  allowed-origin: ${cors.allowed-origin}
