server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

  application:
    name: pet_store_coming_be

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}

  devtools:
    restart:
      enabled: true
